# Generated by Django 4.0 on 2023-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='User Address two', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='User Address two', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='area_name',
            field=models.CharField(blank=True, help_text='User Area Name', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city_name',
            field=models.CharField(blank=True, help_text='User City Name', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='INDIA', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, help_text='User District', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locality',
            field=models.CharField(blank=True, help_text='User Locality', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='User State Name', max_length=30, null=True),
        ),
    ]
