# Generated by Django 4.0 on 2023-07-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_remove_user_status_salonstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.salonname'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.user'),
        ),
        migrations.AlterField(
            model_name='inhouseproductuse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.user'),
        ),
        migrations.AlterField(
            model_name='loyaltypointmaster',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.user'),
        ),
        migrations.AlterField(
            model_name='salaryandcommission',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.salonname'),
        ),
        migrations.AlterField(
            model_name='salaryandcommission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.user'),
        ),
    ]
