# Generated by Django 4.0 on 2023-07-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_attendance_user_alter_inhouseproductuse_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonstaff',
            name='role',
            field=models.CharField(blank=True, help_text='Staff Role', max_length=30, null=True),
        ),
    ]
