# Generated by Django 4.0 on 2023-08-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_salonstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_time',
            field=models.TimeField(blank=True, help_text='Time should be in 18:12:00 this format', null=True),
        ),
    ]
